#!/usr/bin/env bash
#install nginx and run html pages
sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
echo "Hello Omaima! Have a better day" > /var/www/html/index.nginx-debian.html
Hello Omaima! Have a better day