#!/usr/bin/env bash
#commands to automatically configure a Ubuntu machine
sudo apt -y update
sudo apt -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a rewrite ^/error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
