#!/usr/bin/env bash
# kill '4-to_infinity_and_beyond' process
pid_to_kill=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process exists before attempting to kill it
if ps -p "$pid_to_kill" > /dev/null; then
    kill "$pid_to_kill"
else
    exit
fi
