#!/usr/bin/env bash
# A script to print time
h=0
m=0
while [ $h -le 12 ]
do
    echo "hour: $h"
    echo "$m"
    if [ $m -eq 59 ]
    then
        h=$((h+1))
        m=0
    else
        m=$((m+1))
    fi
done