#!/usr/bin/env bash
# A script to print time
h=0
m=0
echo "$h"
echo "$m"
while [ $h -le 12 ]
do
    if [ $m -eq 60 ]
    then
    echo "hour : $h"
    h=$((h+1))
    m=0
    fi
    
    echo "$m"
    m=$((m+1))
    
done